<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.congocc.test</groupId>
  <artifactId>default-config</artifactId>
  <version>1.0.0</version>
  <build>
    <plugins>
      <plugin>
        <groupId>org.congocc</groupId>
        <artifactId>org.congocc.maven.plugin</artifactId>
        <version>2.1.0</version>
      </plugin>
    </plugins>
  </build>
</project>
